#!/usr/bin/env bash

set -euo pipefail

. .env

url="https://adventofcode.com/2025/leaderboard/private/view/296723.json"

curl -b "session=$ADVENT_OF_CODE_SESSION" "$url" -o board.json
./stars --tsv | pbcopy
