#!/usr/bin/env node

import board from './board.json' with { type: 'json' };
import { Temporal } from '@js-temporal/polyfill';
import { Command } from 'commander';

const { values, entries } = Object;

const start = Temporal.PlainDate.from('2025-12-01').toZonedDateTime('America/New_York');

const instant = (seconds) => Temporal.Instant.fromEpochMilliseconds(seconds * 1e3);

const midnight = (day) => start.add({days: day - 1}).toInstant();

const stars = (data) => {
  const ss = values(data.members).flatMap(m => {
    const { name, completion_day_level } = m;
    return perPerson(completion_day_level, name);
  });
  const counts = {};
  return ss.sort((a, b) => a.order - b.order).map(s => {
    const k = key(s);
    const rank = !(k in counts) ? counts[k] = 1 : ++counts[k];
    return { ...s, rank };
  });
};

const perPerson = (completions, name) => {
  return entries(completions).flatMap(([day, parts]) => perDay(parts, Number(day), name));
};

const perDay = (parts, day, name) => {
  return entries(parts).map(([part, {get_star_ts: timestamp, star_index: order }]) => {
    return { name, day, part: Number(part), order, timestamp };
  });
}

const duration = (duration, minUnit = 'second') => {
  const d = duration.round({largestUnit: 'hour', smallestUnit: 'second', roundingMode: 'floor'});
  return `${xx(d.hours, ' ')}:${xx(d.minutes)}:${xx(d.seconds)}`;
}

const xx = (n, p='0') => n.toString().padStart(2, p);

const key = (s) => `d${s.day}p${s.part}`;


const filterByOpts = (opts) => {
  if ('firsts' in opts) {
    const seen = new Set();
    return (s) => {
      const k = key(s);
      if (!seen.has(k)) {
        seen.add(k);
        return true;
      } else {
        return false;
      }
    };
  } else {
    const namePat = opts.name ? new RegExp(opts.name) : /./;
    return (s) => {
      if (opts.day && s.day !== opts.day) return false;
      if (opts.part && s.part !== opts.part) return false;
      if (!namePat.test(s.name)) return false;
      return true;
    };
  }
};

const main = (opts) => {
  const ss = stars(board).filter(filterByOpts(opts));
  for (const s of ss) {
    const elapsed = instant(s.timestamp).since(midnight(s.day));
    if (opts.csv) {
      console.log([s.day, s.part, s.name, s.rank, duration(elapsed)].join(','))
    } else if (opts.tsv) {
      console.log([s.day, s.part, s.name, s.rank, duration(elapsed)].join('\t'))
    } else {
      console.log(`Day ${s.day}, part ${s.part} ${s.name.padEnd(20, ' ')} ${s.rank.toString().padStart(3, ' ')} ${duration(elapsed)}`);
    }
  }
};

new Command()
  .description('Stats about stars')
  .option('-f, --firsts', 'Only first for each star')
  .option('-d, --day <day>', 'Limit to day', Number)
  .option('-p, --part <part>', 'Limit to part', Number)
  .option('-n, --name <name>', 'Limit to user')
  .option('-c, --csv', 'Emit csv')
  .option('-t, --tsv', 'Emit tsv')
  .action(main)
  .parse();
